# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 4nix's blog
email: wublue1234@126.com
description: 5z的博客.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://4nix.github.io" # the base hostname & protocol for your site
github_username:  4nix

# Build settings
markdown: kramdown
layouts_dir: ./_layouts/blog
author: 5z
paginate: 5
paginate_path: "page:num"
gems: [jekyll-paginate]
highlighter: pygments
